### ISSUE TITLE
训练其他验证码出错

### ISSUE THREAD

**Issue by zjcnew** [Jack-Cherish/Deep-Learning#5]
Discuz训练代码我改成训练其他字符验证码，改了数据路径与图片大小，请问这种报错是什么原因呢？

2018-12-25 06:42:58.270255: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 761600 values, but the requested shape requires a multiple of 3328
         [[{{node Reshape_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MaxPool_2, Reshape_1/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 388, in <module>
    m.train_crack_captcha_cnn()
  File "./train.py", line 361, in train_crack_captcha_cnn
    summary, acc = sess.run([merged, accuracy], feed_dict={self.X: batch_x_test, self.Y: batch_y_test, self.keep_prob: 1})
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 761600 values, but the requested shape requires a multiple of 3328
         [[{{node Reshape_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MaxPool_2, Reshape_1/shape)]]

Caused by op 'Reshape_1', defined at:
  File "./train.py", line 388, in <module>
    m.train_crack_captcha_cnn()
  File "./train.py", line 327, in train_crack_captcha_cnn
    model = self.crack_captcha_cnn()
  File "./train.py", line 305, in crack_captcha_cnn
    dense = tf.reshape(conv3, [-1, w_d.get_shape().as_list()[0]])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6296, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 761600 values, but the requested shape requires a multiple of 3328
         [[{{node Reshape_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MaxPool_2, Reshape_1/shape)]]

**Comment by Jack-Cherish** [comment]
这里写着呢：Input to reshape is a tensor with 761600 values, but the requested shape requires a multiple of 3328 
就是大小问题，检查下通道数，节点数和图片是否对应。
